@API_HostAddress = https://localhost:7053
@UserEmail = justinian.erdmier@outlook.com
@UserPassword = MyGigHero@2025

POST {{API_HostAddress}}/register/
Content-Type: application/json

{
  "email": "{{UserEmail}}",
  "password": "{{UserPassword}}"
}

###

POST {{API_HostAddress}}/login?useCookies=true
Content-Type: application/json

{
  "email": "{{UserEmail}}",
  "password": "{{UserPassword}}"
}

###

POST {{API_HostAddress}}/api/gigs/
Content-Type: application/json

{
  "name":       "Rev",
  "websiteUrl": "https://www.rev.com/workspace/dashboard"
}

###

GET {{API_HostAddress}}/api/gigs/

###

@GigId = 019755d9-4757-70b8-97ad-72565f429a52
GET {{API_HostAddress}}/api/gigs/{{GigId}}
